### ISSUE TITLE
"util.print: Use console.log instead" in output

### ISSUE THREAD

**Issue by lipsumar** [testdouble/grunt-jasmine-bundle#10]
When running tests, the output is full of this message: `util.print: Use console.log instead`.

Here is an example:

```
$ grunt test
Running "spec:unit" (spec) task
util.print: Use console.log instead
Futil.print: Use console.log instead

util.print: Use console.log instead

util.print: Use console.log instead
Failures:util.print: Use console.log instead

util.print: Use console.log instead

util.print: Use console.log instead
  1) Exception loading: tests/index.coffee Errorutil.print: Use console.log instead

util.print: Use console.log instead
   Message:util.print: Use console.log instead

util.print: Use console.log instead
     Error: Cannot find module 'underscore'util.print: Use console.log instead

util.print: Use console.log instead
   Stacktrace:util.print: Use console.log instead

util.print: Use console.log instead
     Error: Cannot find module 'underscore'
    at Function.Module._resolveFilename (module.js:336:15)
    at Function.Module._load (module.js:278:25)
    at Module.require (module.js:365:17)
    at require (module.js:384:17)
    at Object.<anonymous> (/Users/emmanuelpire/VirtualBox_shared/sife/index.js:3:6)
    at Module._compile (module.js:460:26)
    at Object.Module._extensions..js (module.js:478:10)
    at Module.load (/Users/emmanuelpire/VirtualBox_shared/sife/node_modules/grunt-jasmine-bundle/node_modules/coffee-script/lib/coffee-script/coffee-script.js:211:36)
    at Function.Module._load (module.js:310:12)
    at Module.require (module.js:365:17)
    at require (module.js:384:17)
    at Object.<anonymous> (/Users/emmanuelpire/VirtualBox_shared/sife/tests/index.coffee:4:10)
    at Object.<anonymous> (/Users/emmanuelpire/VirtualBox_shared/sife/tests/index.coffee:15:4)
    at Module._compile (module.js:460:26)
    at Object.loadFile (/Users/emmanuelpire/VirtualBox_shared/sife/node_modules/grunt-jasmine-bundle/node_modules/coffee-script/lib/coffee-script/coffee-script.js:182:19)
    at Module.load (/Users/emmanuelpire/VirtualBox_shared/sife/node_modules/grunt-jasmine-bundle/node_modules/coffee-script/lib/coffee-script/coffee-script.js:211:36)
    at Function.Module._load (module.js:310:12)
    at Module.require (module.js:365:17)
    at require (module.js:384:17)
    at Object.exports.executeSpecs (/Users/emmanuelpire/VirtualBox_shared/sife/node_modules/grunt-jasmine-bundle/node_modules/minijasminenode/lib/index.js:116:7)
    at Object.<anonymous> (/Users/emmanuelpire/VirtualBox_shared/sife/node_modules/grunt-jasmine-bundle/lib/task-generator.coffee:28:26)
    at Object.<anonymous> (/Users/emmanuelpire/VirtualBox_shared/sife/node_modules/grunt/lib/grunt/task.js:264:15)
    at Object.thisTask.fn (/Users/emmanuelpire/VirtualBox_shared/sife/node_modules/grunt/lib/grunt/task.js:82:16)
    at Object.<anonymous> (/Users/emmanuelpire/VirtualBox_shared/sife/node_modules/grunt/lib/util/task.js:301:30)
    at Task.runTaskFn (/Users/emmanuelpire/VirtualBox_shared/sife/node_modules/grunt/lib/util/task.js:251:24)
    at Task.<anonymous> (/Users/emmanuelpire/VirtualBox_shared/sife/node_modules/grunt/lib/util/task.js:300:12)
    at /Users/emmanuelpire/VirtualBox_shared/sife/node_modules/grunt/lib/util/task.js:227:11
    at process._tickCallback (node.js:355:11)
    at Function.Module.runMain (module.js:503:11)
    at startup (node.js:129:16)
    at node.js:814:3util.print: Use console.log instead


Finished in 0.011 secondsutil.print: Use console.log instead

util.print: Use console.log instead
1 test, 1 assertion, 1 failure
util.print: Use console.log instead

```

**Comment by searls** [comment]
What version of Node are you on? Is this just a new warning?

If it's as simple as changing our own statements, please open a PR. I'm
pretty certain the fault is going to lie with a dependency.

**Comment by jasonkarns** [comment]
Pretty sure this is a dependency thing. `util.print` and friends were deprecated in 0.11 or so. Would also accept a PR that updated the deps, as this issue is likely already fixed in later versions of the deps.
